apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-survey-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: student-survey-app
  template:
    metadata:
      labels:
        app: student-survey-app
    spec:
      containers:
      - name: student-survey-container
        image: ganesh0912/student-survey:latest   # Docker Hub image
        imagePullPolicy: Always                   # Always pull from Docker Hub
        ports:
        - containerPort: 80
